arb-dir: lib/core/l10n
template-arb-file: app_en.arb
untranslated-messages-file: desiredFileName.txt
synthetic-package: false
output-dir: lib/core/l10n/translations
output-localization-file: app_localizations.dart
