// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdisEVyfEBu37a1ynecZ3O05odjozg9WM',
    appId: '1:218566308609:web:d37903731284f59b156100',
    messagingSenderId: '218566308609',
    projectId: 'chat-bot-9654d',
    authDomain: 'chat-bot-9654d.firebaseapp.com',
    storageBucket: 'chat-bot-9654d.firebasestorage.app',
    measurementId: 'G-S3P7VLSSYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrNs3ok2f3UYuE59KJObyYArWfgCuzwxk',
    appId: '1:218566308609:android:cc3a7837f2ee9f81156100',
    messagingSenderId: '218566308609',
    projectId: 'chat-bot-9654d',
    storageBucket: 'chat-bot-9654d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOT4Kk1sTSrj1GiQtLVEQXtAeFj9Jw_WQ',
    appId: '1:218566308609:ios:e0d22e9aefcf39d1156100',
    messagingSenderId: '218566308609',
    projectId: 'chat-bot-9654d',
    storageBucket: 'chat-bot-9654d.firebasestorage.app',
    iosBundleId: 'com.example.chatBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOT4Kk1sTSrj1GiQtLVEQXtAeFj9Jw_WQ',
    appId: '1:218566308609:ios:e0d22e9aefcf39d1156100',
    messagingSenderId: '218566308609',
    projectId: 'chat-bot-9654d',
    storageBucket: 'chat-bot-9654d.firebasestorage.app',
    iosBundleId: 'com.example.chatBot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdisEVyfEBu37a1ynecZ3O05odjozg9WM',
    appId: '1:218566308609:web:81c1d45dacd474f4156100',
    messagingSenderId: '218566308609',
    projectId: 'chat-bot-9654d',
    authDomain: 'chat-bot-9654d.firebaseapp.com',
    storageBucket: 'chat-bot-9654d.firebasestorage.app',
    measurementId: 'G-NE277H5D55',
  );
}
